spring:
  profile.active: dev
  datasource:
    url: jdbc:mysql://localhost/forohub
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:123456}

#spring.application.name=ForoHub
